networks:
  redcanyon-net:
    driver: bridge

services:
  app:
    container_name: redcanyon
    build:
      dockerfile: Dockerfile
      args:
        # - BUILDPLATFORM=linux/amd64
        - BUILDPLATFORM=linux/arm64
    ports:
      - 5173:5173
      - 4200:4200
      - 6379:6379
      - 8005:8001
    expose:
      - 4200
      - 6379
    volumes:
      - ./red-canyon-web:/project/app
      - ./server:/project/server
    networks:
      - redcanyon-net
    env_file:
      - .env
