networks:
  redcanyon-net:
    driver: bridge

services:
  web:
    build:
      context: vuejs
      target: development
    ports:
      - 8080:8080
    volumes:
      - ./vuejs:/project
      - /project/node_modules
    networks:
      - redcanyon-net
  server:
    ports:
      - 4200:4200
    volumes:
      - ./server:/project
    build:
      context: ./server
      dockerfile_inline: |
        FROM node:22-bookworm-slim
        WORKDIR /project
        COPY package.json package-lock.json /project/
        RUN pwd
        RUN ls .
        RUN npm install
    command: npm run dev -- --host=0.0.0.0
    networks:
      - redcanyon-net

