networks:
  redcanyon-net:
    driver: bridge

services:
  web:
    container_name: redcanyon-web
    build:
      context: red-canyon-web
      target: development
    ports:
      - 5173:5173
    volumes:
      - ./red-canyon-web:/project
      - /project/node_modules
    networks:
      - redcanyon-net
  server:
    container_name: redcanyon-api
    ports:
      - 4200:4200
    expose:
      - 4200
    volumes:
      - ./server:/project
    build:
      context: ./server
      dockerfile_inline: |
        FROM node:22-bookworm-slim
        RUN mkdir /project
        WORKDIR /project
        COPY . .
        RUN npm install
    command: npm run dev -- --host=0.0.0.0
    networks:
      - redcanyon-net
  # https://zomro.com/blog/faq/301-kak-ustanovit-redis-v-docker#:~:text=Docker%20Compose%20will%20automatically%20download,yaml%20file.&text=You%20can%20connect%20to%20the,defined%20in%20the%20docker%2Dcompose.
  # docker exec -it red-canyon-cache redis-cli
  cache:
    container_name: redcanyon-cache
    image: redis:latest
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    restart: unless-stopped
    ports:
      - 6379:6379
      - 8005:8001
    expose:
      - 6379
    volumes:
      - ./cache:/root/redis
    networks:
      - redcanyon-net
