networks:
  redcanyon-net:
    driver: bridge

services:
  web:
    container_name: vue-web
    build:
      context: red-canyon-web
      target: development
    ports:
      - 5173:5173
    volumes:
      - ./red-canyon-web:/project
      - /project/node_modules
    networks:
      - redcanyon-net
  server:
    container_name: places-api
    ports:
      - 4200:4200
    expose:
      - 4200
    volumes:
      - ./server:/project
    build:
      context: ./server
      dockerfile_inline: |
        FROM node:22-bookworm-slim
        RUN mkdir /project
        WORKDIR /project
        COPY . .
        RUN npm install
    command: npm run dev -- --host=0.0.0.0
    networks:
      - redcanyon-net
